version: '2'
services:
  web:
    container_name: lyeung-jenkins
    build: lyeung-jenkins
    image: lyeung-jenkins
    links:
      - redis
    ports:
      - '50000:50000'
      - '9080:8080'
    volumes:
      - ~/docker-jenkins:/var/jenkins_home
    networks:
      lyeung-jenkins-network:
        ipv4_address: 172.25.1.2
  redis:
#    container: lyeung-jenkins-redis
    build: lyeung-jenkins-redis
    image: lyeung-jenkins-redis
    ports:
      - '16379:6379'
    volumes:
      - $HOME/docker-redis:/data
    networks:
      lyeung-jenkins-network:
        ipv4_address: 172.25.2.2

networks:
  lyeung-jenkins-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1
